name: Build docker image and push to docker hub

on:
  push:
    branches: [ test_deployment ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: npm run docker:build

      - name: Push the Docker image to the repository
        run: npm run docker:push